### ISSUE TITLE
Hands tied together when shrinking avatars

### ISSUE THREAD

**Issue by madjin** [exokitxr/avatars#25]
When I shrink any of the polygonal mind avatars in desktop mode, the hands sorta cuff together.
![](https://i.imgur.com/XikWxVS.jpg)

![](https://i.imgur.com/BHVyiEK.jpg)

**Comment by modulesio** [comment]
Should be fixed with https://github.com/exokitxr/avatars/commit/3e8b6713bdfe75fb97aed52a380785e7f0f44878.
