### ISSUE TITLE
Rapunzel hair too cray

### ISSUE THREAD

**Issue by modulesio** [exokitxr/avatars#5]
Hair physics need to be toned down to restitute more against the headpose, or self-intersect, so that they don't get in the way of the player's view.

**Comment by modulesio** [comment]
Also, when looking at the player scaled down, the hair scale is completely out of what with the rest of the avatar (it is basically not scaled).

**Comment by modulesio** [comment]
This should be fixed now for the hair scaling case. Hair physics downplaying would be a separate issue.

**Comment by ChrisEddy** [comment]
Nice work.
