### ISSUE TITLE
Disable Decapitation?

### ISSUE THREAD

**Issue by chrismatthieu** [exokitxr/avatars#8]
Hats off! This project is amazing! 

How do we disable decapitation mode? It doesn't look right on PCs.

**Comment by avaer** [comment]
This is documented in the readme.

**Comment by chrismatthieu** [comment]
decapitate: false doesn't seem to bring the head back...

**Comment by modulesio** [comment]
Should be fixed now, and the default is to not decapitate on the demo page.
